/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    branches: Branch;
    rooms: Room;
    tenants: Tenant;
    invoices: Invoice;
    contracts: Contract;
    'maintenance-tickets': MaintenanceTicket;
    'device-tokens': DeviceToken;
    'otp-verifications': OtpVerification;
    'utility-logs': UtilityLog;
    'utility-anomalies': UtilityAnomaly;
    payments: Payment;
    notifications: Notification;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    branches: BranchesSelect<false> | BranchesSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    contracts: ContractsSelect<false> | ContractsSelect<true>;
    'maintenance-tickets': MaintenanceTicketsSelect<false> | MaintenanceTicketsSelect<true>;
    'device-tokens': DeviceTokensSelect<false> | DeviceTokensSelect<true>;
    'otp-verifications': OtpVerificationsSelect<false> | OtpVerificationsSelect<true>;
    'utility-logs': UtilityLogsSelect<false> | UtilityLogsSelect<true>;
    'utility-anomalies': UtilityAnomaliesSelect<false> | UtilityAnomaliesSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  phone?: string | null;
  fullName?: string | null;
  role: 'super_admin' | 'manager' | 'tenant';
  /**
   * Cơ sở mà User này trực thuộc
   */
  branch?: (number | null) | Branch;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches".
 */
export interface Branch {
  id: number;
  name: string;
  address?: string | null;
  phone?: string | null;
  description?: string | null;
  status?: ('active' | 'inactive') | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  cloudinaryUrl?: string | null;
  cloudinaryPublicId?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  /**
   * Co so chua phong nay
   */
  branch: number | Branch;
  roomCode: string;
  floor?: number | null;
  area?: number | null;
  basePrice: number;
  electricPrice?: number | null;
  waterPrice?: number | null;
  status?: ('available' | 'occupied' | 'maintenance') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Tài khoản đăng nhập của khách thuê này
   */
  user: number | User;
  room: number | Room;
  identityNumber: string;
  emergencyContact?: string | null;
  moveInDate: string;
  moveOutDate?: string | null;
  idCardImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  invoiceCode: string;
  room: number | Room;
  tenant?: (number | null) | Tenant;
  utilityLog?: (number | null) | UtilityLog;
  roomPrice: number;
  electricCost?: number | null;
  waterCost?: number | null;
  serviceCost?: number | null;
  totalAmount: number;
  paymentStatus?: ('unpaid' | 'partial' | 'paid') | null;
  issuedAt?: string | null;
  paidAt?: string | null;
  qrPayload?: string | null;
  checkoutUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utility-logs".
 */
export interface UtilityLog {
  id: number;
  room: number | Room;
  month: number;
  year: number;
  electricOld: number;
  electricNew: number;
  electricUsage?: number | null;
  waterOld: number;
  waterNew: number;
  waterUsage?: number | null;
  recordedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts".
 */
export interface Contract {
  id: number;
  contractCode: string;
  tenant: number | Tenant;
  room: number | Room;
  startDate: string;
  endDate?: string | null;
  depositAmount?: number | null;
  monthlyPrice?: number | null;
  status?: ('active' | 'expired' | 'terminated') | null;
  images?:
    | {
        image: number | Media;
        pageNumber?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-tickets".
 */
export interface MaintenanceTicket {
  id: number;
  title: string;
  description: string;
  priority?: ('low' | 'medium' | 'high' | 'urgent') | null;
  status?: ('open' | 'in-progress' | 'resolved') | null;
  tenant: number | Tenant;
  room: number | Room;
  assignedManager?: (number | null) | User;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-tokens".
 */
export interface DeviceToken {
  id: number;
  token: string;
  /**
   * Điền nếu đây là thiết bị của Quản lý
   */
  user?: (number | null) | User;
  /**
   * Điền nếu đây là thiết bị của Cư dân
   */
  tenant?: (number | null) | Tenant;
  platform?: ('ios' | 'android' | 'web') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-verifications".
 */
export interface OtpVerification {
  id: number;
  phone: string;
  otpCode: string;
  purpose?: ('login' | 'register') | null;
  expiredAt: string;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utility-anomalies".
 */
export interface UtilityAnomaly {
  id: number;
  utilityLog: number | UtilityLog;
  type: 'electric' | 'water';
  severity: 'warning' | 'critical';
  message?: string | null;
  resolved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  invoice: number | Invoice;
  bankCode?: string | null;
  transactionCode?: string | null;
  amount: number;
  paidAt: string;
  rawPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  title: string;
  body?: string | null;
  type?: ('invoice' | 'maintenance' | 'system') | null;
  isRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  user?: (number | null) | User;
  action: 'create' | 'update' | 'delete' | 'login';
  entityType?: string | null;
  entityId?: string | null;
  oldData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  newData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'branches';
        value: number | Branch;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'contracts';
        value: number | Contract;
      } | null)
    | ({
        relationTo: 'maintenance-tickets';
        value: number | MaintenanceTicket;
      } | null)
    | ({
        relationTo: 'device-tokens';
        value: number | DeviceToken;
      } | null)
    | ({
        relationTo: 'otp-verifications';
        value: number | OtpVerification;
      } | null)
    | ({
        relationTo: 'utility-logs';
        value: number | UtilityLog;
      } | null)
    | ({
        relationTo: 'utility-anomalies';
        value: number | UtilityAnomaly;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  phone?: T;
  fullName?: T;
  role?: T;
  branch?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinaryUrl?: T;
  cloudinaryPublicId?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branches_select".
 */
export interface BranchesSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  phone?: T;
  description?: T;
  status?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  branch?: T;
  roomCode?: T;
  floor?: T;
  area?: T;
  basePrice?: T;
  electricPrice?: T;
  waterPrice?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  user?: T;
  room?: T;
  identityNumber?: T;
  emergencyContact?: T;
  moveInDate?: T;
  moveOutDate?: T;
  idCardImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceCode?: T;
  room?: T;
  tenant?: T;
  utilityLog?: T;
  roomPrice?: T;
  electricCost?: T;
  waterCost?: T;
  serviceCost?: T;
  totalAmount?: T;
  paymentStatus?: T;
  issuedAt?: T;
  paidAt?: T;
  qrPayload?: T;
  checkoutUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts_select".
 */
export interface ContractsSelect<T extends boolean = true> {
  contractCode?: T;
  tenant?: T;
  room?: T;
  startDate?: T;
  endDate?: T;
  depositAmount?: T;
  monthlyPrice?: T;
  status?: T;
  images?:
    | T
    | {
        image?: T;
        pageNumber?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-tickets_select".
 */
export interface MaintenanceTicketsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  priority?: T;
  status?: T;
  tenant?: T;
  room?: T;
  assignedManager?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-tokens_select".
 */
export interface DeviceTokensSelect<T extends boolean = true> {
  token?: T;
  user?: T;
  tenant?: T;
  platform?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-verifications_select".
 */
export interface OtpVerificationsSelect<T extends boolean = true> {
  phone?: T;
  otpCode?: T;
  purpose?: T;
  expiredAt?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utility-logs_select".
 */
export interface UtilityLogsSelect<T extends boolean = true> {
  room?: T;
  month?: T;
  year?: T;
  electricOld?: T;
  electricNew?: T;
  electricUsage?: T;
  waterOld?: T;
  waterNew?: T;
  waterUsage?: T;
  recordedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utility-anomalies_select".
 */
export interface UtilityAnomaliesSelect<T extends boolean = true> {
  utilityLog?: T;
  type?: T;
  severity?: T;
  message?: T;
  resolved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  invoice?: T;
  bankCode?: T;
  transactionCode?: T;
  amount?: T;
  paidAt?: T;
  rawPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  title?: T;
  body?: T;
  type?: T;
  isRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  user?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  oldData?: T;
  newData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}