-- ==============================================================================
-- 2. TẠO BẢNG BRANCHES (CHI NHÁNH) & THIẾT LẬP RÀNG BUỘC BẢO MẬT RLS
-- ==============================================================================

-- A. Tạo bảng branches nếu chưa tồn tại
CREATE TABLE IF NOT EXISTS branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  phone TEXT,
  description TEXT,
  status TEXT DEFAULT 'active' NOT NULL,
  created_by_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- B. Bật RLS (Row Level Security) cho bảng branches
ALTER TABLE branches ENABLE ROW LEVEL SECURITY;

-- C. Tạo chính sách RLS cho phép truy cập nếu đã đăng nhập
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'branches' AND policyname = 'Cho phép đọc/ghi chi nhánh nếu đã đăng nhập'
  ) THEN
    CREATE POLICY "Cho phép đọc/ghi chi nhánh nếu đã đăng nhập" 
    ON branches 
    FOR ALL 
    TO authenticated 
    USING (auth.uid() IS NOT NULL);
  END IF;
END
$$;

-- D. Thêm ràng buộc khóa ngoại cho bảng public.users nếu chưa tồn tại
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'fk_users_branch'
  ) THEN
    ALTER TABLE users 
    ADD CONSTRAINT fk_users_branch 
    FOREIGN KEY (branch_id) 
    REFERENCES branches(id) 
    ON DELETE SET NULL;
  END IF;
END
$$;
